sudo: required
services:
  - docker

before_install:
  - docker build -t meraj90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true meraj90/react-test npm test

after_success:
  - docker build -t meraj90/multi-client ./client
  - docker build -t meraj90/multi-nginx ./nginx
  - docker build -t meraj90/multi-server ./server
  - docker build -t meraj90/multi-worker ./worker
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to Docker Hub
  - docker push meraj90/multi-nginx
  - docker push meraj90/multi-server
  - docker push meraj90/multi-worker
  - docker push meraj90/multi-client

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-032125308766
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY